### ISSUE TITLE
Some errors trying to append to master 2.91

### ISSUE THREAD

**Issue by tin2tin** [sungreen/DomIK#1]
Very interesting project. Some errors trying to append to master 2.91:

![image](https://user-images.githubusercontent.com/1322593/93010563-5517b680-f58e-11ea-85a7-41e5b7fee545.png)

If you want to test the waters if this is something which could be included in Blender, you can ask in the VSE chat here: https://blender.chat/ ISS is the maintainer of the VSE.

Still works, tho.

**Comment by sungreen** [comment]
Fix splash error.
Now use only default splash.png

https://github.com/sungreen/DomIK/blob/master/291-20200913.diff

**Comment by tin2tin** [comment]
Thank you. Works really well and surprising feature rich. I've tweeted about it, and I hope that will make more people get to know you work.
